
# Some constants used for reading layers and layer properties from CFG file
LAYER_CONVOLUTIONAL = 'convolutional'
LAYER_UPSAMPLE = 'upsample'
LAYER_ROUTE = 'route'
LAYER_SHORTCUT = 'shortcut'
LAYER_MAX_POOL = 'maxpool'
LAYER_YOLO = 'yolo'
LAYER_NET = 'net'
LAYER_LEAKY = 'leaky'
LAYER_RELU = 'relu'
LAYER_LINEAR = 'linear'

LPROP_ACTIVATION = 'activation'
LPROP_STRIDE = 'stride'
LPROP_TYPE = 'type'
LPROP_BATCH_NORMALIZE = 'batch_normalize'
LPROP_FILTERS = 'filters'
LPROP_PAD = 'pad'
LPROP_LAYERS = 'layers'
LPROP_SIZE = 'size'
LPROP_ANCHORS = 'anchors'
LPROP_FROM = 'from'
LPROP_MASK = 'mask'
LPROP_HEIGHT = 'height'
LPROP_CLASSES = 'classes'

# some constants for reading the data config file
BASE_PATH = 'base_path'
CONF_NAMES = 'names'
CFG = 'cfg'
CONF_WEIGHTS = 'weights'
